"""Константы среды обучения."""

import numpy as np

# Ограничение скорости накачки/откачки воздуха в баллон (кг/с).
ACTION_LIMIT = 5.0
DEFAULT_DT = 0.5
# 2 500 000 шагов × dt=0.5 с ≈ 14.5 суток симуляции на эпизод (eval / верхняя граница).
MAX_EPISODE_STEPS = 2_500_000
# Лимит шагов эпизода при обучении PPO.
TRAIN_MAX_EPISODE_STEPS = 2_500_000
# Куррикулум длины эпизода (не менять без явного запроса).
TRAIN_EPISODE_LENGTH_CURRICULUM_MIN = 300_000
TRAIN_EPISODE_LENGTH_CURRICULUM_MAX = 1_250_000
TRAIN_EPISODE_LENGTH_CURRICULUM_STEP = 200_000
TRAIN_EPISODE_LENGTH_CURRICULUM_INTERVAL = 1_000_000
TRAIN_EPISODE_LENGTH_CURRICULUM_INTERVAL_GROWTH = 2_000_000
# Горизонтальный progress (Δdist_xy, м) / scale; асимметричные веса — см. EnvironmentConfig.
REWARD_HORIZONTAL_PROGRESS_SCALE = 200.0
REWARD_VERTICAL_PROGRESS_SCALE = 4000.0
# Зональные множители horizontal progress по dist_xy (м).
REWARD_PROGRESS_ZONE_FAR_M = 20_000.0
REWARD_PROGRESS_ZONE_MID_M = 5_000.0
REWARD_PROGRESS_ZONE_NEAR_M = 1_000.0
REWARD_PROGRESS_ZONE_MID_MULT = 3.0
REWARD_PROGRESS_ZONE_NEAR_MULT = 10.0
REWARD_PROGRESS_ZONE_FINISH_MULT = 25.0
# Слабый фон −distance_xy; доп. квадратичный штраф ближе к цели.
REWARD_HORIZONTAL_DISTANCE_SCALE = 75_000.0
REWARD_HORIZONTAL_DISTANCE_COEF = 0.01
REWARD_DISTANCE_NEAR_RADIUS_M = 50_000.0
REWARD_DISTANCE_NEAR_QUAD_COEF = 0.5
# Ветер к цели (м/с) / scale; Δalignment; бонус за новый минимум dist_xy (затухающий).
REWARD_WIND_ALIGN_SCALE = 20.0
REWARD_WIND_ALIGN_COEF = 0.5
REWARD_WIND_ALIGN_DELTA_COEF = 0.25
REWARD_WIND_ALIGN_ADVERSE_PROGRESS_SCALE = 0.25
REWARD_WIND_ALIGN_ZERO_PROGRESS_STEPS = 5
REWARD_WIND_FAVORABLE_THRESHOLD = 0.0
REWARD_WIND_ADVERSE_THRESHOLD = -5.0
REWARD_WIND_FAVORABLE_STREAK_STEPS = 80
REWARD_WIND_ADVERSE_STREAK_STEPS = 200
REWARD_WIND_FAVORABLE_STREAK_BONUS = 0.04
REWARD_WIND_ADVERSE_STREAK_PENALTY = 0.1
REWARD_HORIZONTAL_PROGRESS_POS_COEF = 3.0
REWARD_HORIZONTAL_PROGRESS_NEG_COEF = 0.4
REWARD_VERTICAL_PROGRESS_POS_COEF = 0.25
REWARD_VERTICAL_PROGRESS_NEG_COEF = 0.05
REWARD_BEST_DISTANCE_BONUS = 20.0
REWARD_BEST_DISTANCE_MAX_DIST_M = 50_000.0
# Штраф за откат от лучшего dist_xy (ограниченный, чтобы не ломать critic).
REWARD_DISTANCE_REGRESSION_COEF = 0.03
REWARD_DISTANCE_REGRESSION_SCALE_M = 1_000.0
REWARD_DISTANCE_REGRESSION_MIN_M = 500.0
REWARD_DISTANCE_REGRESSION_MAX_TERM = 1.0
REWARD_DISTANCE_REGRESSION_REL_RATIO = 1.05
REWARD_HOLD_CLOSE_RADIUS_M = 5_000.0
REWARD_HOLD_CLOSE_BONUS = 0.05
REWARD_ENERGY_COEF = 0.5
REWARD_ENERGY_SCALE = 100.0
REWARD_BOUNDARY_PENALTY = 0.05
# Штраф за полёт выше порога во встречном ветре.
REWARD_HIGH_ALTITUDE_M = 5000.0
REWARD_HIGH_ALTITUDE_ADVERSE_PENALTY = 0.05
# Доп. штраф: высоко + отриц. progress (анти-потолок).
REWARD_CEILING_ALTITUDE_M = 8_000.0
REWARD_CEILING_ADVERSE_PROGRESS_PENALTY = 0.3
REWARD_Z_MAX_CEILING_RATIO = 0.9
REWARD_Z_MAX_CEILING_PENALTY = 0.15
REWARD_IDLE_ACTION_THRESHOLD = 0.3
REWARD_IDLE_ACTION_MIN_DZ_M = 0.1
REWARD_IDLE_ACTION_STREAK_STEPS = 40
REWARD_IDLE_ACTION_PENALTY = 0.02
# Бонус за улучшение wind_toward после смены слоя (|Δz| ≥ порога).
REWARD_WIND_SCAN_MIN_DZ_M = 10.0
REWARD_WIND_SCAN_DELTA_COEF = 2.0
# Постоянный shaping: «в probe-слоях ветер лучше, чем сейчас».
REWARD_WIND_PROBE_BEST_COEF = 0.08
REWARD_WIND_PROBE_BEST_MIN_DELTA = 0.5
REWARD_ADVERSE_WIND_CLOSE_RADIUS_M = 10_000.0
REWARD_ADVERSE_WIND_CLOSE_PENALTY = 0.15
# z_stick: не штрафовать, если за recent-окно была смена слоя.
REWARD_Z_STICK_WINDOW_STEPS = 50_000
REWARD_Z_STICK_MIN_STD_M = 200.0
REWARD_Z_STICK_PENALTY = 0.03
REWARD_Z_STICK_RECENT_WINDOW_STEPS = 1_000
REWARD_Z_STICK_RECENT_DZ_MIN_M = 50.0
# Штраф за «залипание у земли» далеко от цели; бонус за подъём к лучшему probe-слою.
REWARD_LOW_ALTITUDE_M = 500.0
REWARD_LOW_ALTITUDE_FAR_M = 10_000.0
REWARD_LOW_ALTITUDE_STUCK_PENALTY = 0.05
REWARD_CLIMB_TOWARD_WIND_COEF = 0.15
REWARD_CLIMB_TOWARD_WIND_MIN_DZ_M = 5.0
SUCCESS_REWARD = 500.0
OBS_XY_SCALE = 75_000.0
OBS_ALTITUDE_SCALE = 15_000.0
OBS_WIND_SCALE = 50.0
OBS_VERTICAL_SPEED_SCALE = 10.0
OBS_VERTICAL_ACCELERATION_SCALE = 2.0
OBS_ENERGY_SCALE = 1_000_000.0
OBS_AIR_WEIGHT_SCALE = 1_000.0
OBS_AIR_DENSITY_SCALE = 2.0
OBS_TEMPERATURE_SCALE = 300.0
OBS_PRESSURE_SCALE = 100_000.0
OBS_NAV_DISTANCE_SCALE = 50_000.0
OBS_PROBE_ALTITUDES_M: tuple[float, ...] = (500.0, 1500.0, 3000.0, 10_000.0)
# base(20) + probe(N) + nav(2) + probe_gradients(N-1)
OBS_DIM = 20 + len(OBS_PROBE_ALTITUDES_M) + 2 + max(0, len(OBS_PROBE_ALTITUDES_M) - 1)
TARGET_REACH_RADIUS = 25.0
TARGET_REACH_RADIUS_INITIAL = 100.0
TARGET_REACH_RADIUS_FINAL = 25.0
TARGET_VERTICAL_REACH_RADIUS = 3000.0
TRAIN_INITIAL_POSITION_DELTA = np.array([8_000.0, 8_000.0, 0.0], dtype=np.float32)
TRAIN_TARGET_POSITION_DELTA = np.array([8_000.0, 8_000.0, 1_500.0], dtype=np.float32)
